//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class danhgia
    {
        public string manb { get; set; }
        public string manm { get; set; }
        public int rating { get; set; }
    
        public virtual nguoiban nguoiban { get; set; }
        public virtual nguoimua nguoimua { get; set; }
    }
}
