//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadontk
    {
        public string mahd { get; set; }
        public string manb { get; set; }
        public System.DateTime ngay { get; set; }
        public int giatri { get; set; }
    
        public virtual nguoiban nguoiban { get; set; }
    }
}
