//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTDD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DTDDEntities : DbContext
    {
        public DTDDEntities()
            : base("name=DTDDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cthoadon> cthoadons { get; set; }
        public virtual DbSet<danhgia> danhgias { get; set; }
        public virtual DbSet<giohang> giohangs { get; set; }
        public virtual DbSet<hoadon> hoadons { get; set; }
        public virtual DbSet<hoadontk> hoadontks { get; set; }
        public virtual DbSet<nguoiban> nguoibans { get; set; }
        public virtual DbSet<nguoimua> nguoimuas { get; set; }
        public virtual DbSet<sanpham> sanphams { get; set; }
    }
}
