//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanpham()
        {
            this.cthoadons = new HashSet<cthoadon>();
            this.giohangs = new HashSet<giohang>();
        }
        
        public string masp { get; set; }
        public string tensp { get; set; }
        public string math { get; set; }
        public Nullable<int> gia { get; set; }
        public byte[] hinh { get; set; }
        public string loai { get; set; }
        public string kco { get; set; }
        public string pgiai { get; set; }
        public string hdh { get; set; }
        public string cpu { get; set; }
        public string ram { get; set; }
        public string bnho { get; set; }
        public string camera { get; set; }
        public Nullable<int> pin { get; set; }
        public int tinhtrang { get; set; }
        public string manb { get; set; }
        public int soluong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cthoadon> cthoadons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giohang> giohangs { get; set; }
        public virtual nguoiban nguoiban { get; set; }
    }
}
